name: test
on:
  push:
    branches: # when new release is out - update these and if conditions below
      - "main"
      - "release/*"
    paths: # it makes sense to only run this job if node packages config changes, or job's config changes
      - "index.html"
      - ".github/workflows/main.yml"
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ref name
        run: echo ${{ github.ref }}
      - name: Commit Legal Notice
        run: |
          git branch
